title: Didattica online
email: emergenza.didattica.online@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Uno "sportello di aiuto" per la realizzazione della didattica a distanza e didattica online
baseurl: "/didattica-online-website" # the subpath of your site, e.g. /blog
url: "https://thezingaro.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima

# minima theme settings
show_excerpts: true # set to true to show excerpts on the homepage
disqus:
  shortname: didatticaonline

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

permalink: /:categories/:slug:output_ext

collections:
  categories:
    output: true
    permalink: /:name/

defaults: 
  - scope:
      path: "_categories"
      type: categories
    values:
      layout: category
      
google_analytics: UA-112361799-4
