title: Didattica online
email: emergenza.didattica.online@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Uno "sportello di aiuto" per la realizzazione della didattica a distanza e didattica online
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://didatticaonline.netlify.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima

# minima theme settings
show_excerpts: true # set to true to show excerpts on the homepage
disqus:
  shortname: didatticaonline-netlify-com

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
